home: notify

diff --git a/home/update-any b/home/update-any
--- a/home/update-any
+++ b/home/update-any
@@ -1,11 +1,13 @@
 #!/bin/bash
 
+set -e
+
 if [[ -e "$HOME/.secret" ]]; then
   cd "$HOME/.secret"
-  git pull
+  git pull || echo "Cannot update secret: $?" >> "$MSGFILE"
 fi
 if command -v pass >/dev/null 2>&1; then
-  pass git pull
+  pass git pull || echo "Cannot update pass: $?" >> "$MSGFILE"
 fi
 
 exit 0
